version: "3"
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "scheduledb"
    ports:
      - "5432:5432"
  api:
    image: yaroslavholota/pes_api:latest
    environment:
      Port: 5432
      User: postgres
      Password: password
      Host: "postgresdb"
      DB: "PesDb"
      InitializeDb: "true"
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - "postgresdb"
    restart: unless-stopped
