version: "3"
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "PesDb"
    ports:
      - "1233:5432"
  api:
    build: ./
    environment:
      Port: 5432
      User: postgres
      Password: password
      Host: "postgresdb"
      DB: "PesDb"
      InitializeDb: "true"
      SwaggerIncluded: "true"
    ports:
      - "5000:443"
      - "1234:80"
    depends_on:
      - "postgresdb"
    restart: unless-stopped
